### ISSUE TITLE
Python 3 and prestashop 1.6 support ?

### ISSUE THREAD

**Issue by hadim** [prestapyt/prestapyt#25]
All is in the title :-)

**Comment by eliasrodeloso** [comment]
I was using prestapyt without troubles in Python 2 but now I need it for Python 3.5, so...
@guewen is it already working with Python 3?

**Comment by rajaranjan-s** [comment]
No It is not working ..Anybody found a solution to this?

**Comment by qtheuret** [comment]
I make a migration of code to make it compatible with Python 3 : https://github.com/prestapyt/prestapyt/pull/48

**Comment by capiscuas** [comment]
Thanks @qtheuret , I needed that for some Woocomerce -> Prestashop migration using python3.5

I installed it using 
`pip install https://github.com/qtheuret/prestapyt/archive/migration-py3.zip
`

**Comment by GuillaumeDesforges** [comment]
3 years later, package is still not Python 3 compatible ?

**Comment by guewen** [comment]
Hi, personally I do no longer participate in the development of the library.
Maybe @bguillot or @pedrobaeza do, but IMO it is worth considering additional maintainers to step in.

**Comment by pedrobaeza** [comment]
I'm also not very active on this side, as we don't keep PrestaShop connector, but I can review PRs adding such things. I think some work is already done anyway.

**Comment by GuillaumeDesforges** [comment]
What about merging @qtheuret 's work ?

**Comment by pedrobaeza** [comment]
AFAIK, #48 is merged

**Comment by GuillaumeDesforges** [comment]
Oh, thanks!

**Comment by pedrobaeza** [comment]
Checking, both are merged, so we can close this. The library must be install from sources, not from pypi though, but that's another topic.
