### ISSUE TITLE
'utf8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by dorcy-v** [prestapyt/prestapyt#31]
Hello,

I have a probleme when I try associate an image to a product.

```python
fd       = io.open(image_fr.filename, "rb")
content  = fd.read()
fd.close()
connetion.add('/images/products/'+str(id_product), files=[('image', name, content)])

```
I have this error: ''utf8' codec can't decode byte 0xff in position 0: invalid start byte' on "/prestapyt.py", line 420, in encode_multipart_formdata

**Comment by dorcy-v** [comment]
It's okay finally

**Comment by auveele** [comment]
Hi!
I'va got the same problem, but I can't fix it.
How did you fix it..?

Thanks in advance.

**Comment by dorcyv** [comment]
Hi!
I think it was a problem with the image name...
