### ISSUE TITLE
cannot import name 'PrestaShopWebService'

### ISSUE THREAD

**Issue by jcohenar** [prestapyt/prestapyt#32]
Hi, I'm following the instructions to install and run prestapyt but getting the following error

>>> from prestapyt import PrestaShopWebService
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    from prestapyt import PrestaShopWebService
  File "C:\Python34\lib\site-packages\prestapyt\__init__.py", line 1, in <module>
    from prestapyt import PrestaShopWebService
ImportError: cannot import name 'PrestaShopWebService'

I'm running Python 3.4 in Windows 10 and the version of my Prestashop is 1.6

Any hint on what I am doing wrong? 

thanks in advance

**Comment by guewen** [comment]
Hi,

This library has not been ported to Python 3.

I'm no longer maintaining this library and am willing to hand over if someone motivated wants to become a maintainer.

**Comment by Firiyuu** [comment]
@guewen I want to port this library to Python3 from the curse of 2.7. This is pretty useful for my work right now, care to make me a maintainer?

**Comment by GuillaumeDesforges** [comment]
@Firiyuu any news about porting it to Python 3 ?
