### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by InQuartic** [prestapyt/prestapyt#47]
prestapyt.prestapyt.PrestaShopAuthenticationError: 'Unauthorized'

I have tried to connect to the API through through standards requests and works fine. When i tried using the library i get and Unauthorized Error. I used the example and C+P'ed my details in.

**Comment by pedrobaeza** [comment]
This seems to be a problem in your end, about configuring correctly the permissions for accessing Prestashop outside (the web sevice).

Closing right now as nothing indicates about a problem itself in the library.
