### ISSUE TITLE
CRLF.join(L)  expected str instance, bytes found when uploading image

### ISSUE THREAD

**Issue by capiscuas** [prestapyt/prestapyt#49]
I am trying to upload images inside a product of prestashop 1.7.4 (I know it's not fully supported yet, but the rest of the methods worked like charm, adding or editing other structures even with dict)
`prestashop.add('/images/products/{}'.format(new_product_id), files=[('image', 'image.jpg', content)])`

but I get the following error:
```
  File "/site-packages/prestapyt/prestapyt.py", line 499, in encode_multipart_formdata
    body = CRLF.join(L)
TypeError: sequence item 4: expected str instance, bytes found
```
which is due to the fact that  **L.append(value)** is a binary data and during that join it gets mixed with string data and fails.

I was able to solve the image upload directly with the requests module(which I belive it's used within prestapyt in the following way:

```
ps_token = 'XXXXXXXXXXXXXXXXXXx'
ps_image_url = 'http://xxxxxxx/images/products/{}'.format(new_product_id)
filename = '/tmp/filename.jpg'
files = {'image': ("filename.jpg", open(file_name, 'rb'), 'image/jpg')}

client = requests.Session()
client.auth = (ps_token, '')
r = client.post(ps_image_url, files=files)
print(r)
print(r.text)
```

I am not sure if it is a python3 issue(I am using the port version recenlty made) only. But I'm writting this because I think this python library is awesome and makes the API so easy to use with dictionaries. Thanks for your comments or some possible pull request.

**Comment by highhigh** [comment]
Any update on this? I encountered the same error message when uploading a video.

**Comment by qtheuret** [comment]
HI,

In Python 2.7, 'str' type is a string and you have to decode it to get 'unicode'.
In Python 3, strings are by default 'unicode' type and you have to encode it to get 'str'.

So, you have to encode your `open(file_name, 'rb')` to get 'str'.

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

The usage example to add a product image still doesn't work for Python 3:

https://github.com/prestapyt/prestapyt#add-product-image

```
>>> import io
>>> import prestapyt
>>> from prestapyt import PrestaShopWebServiceDict
>>> prestashop = PrestaShopWebServiceDict('https://.../api', '...')
>>> file_name = '20108.jpg'
>>> fd = io.open(file_name, "rb")
>>> content = fd.read()
>>> fd.close()
>>> prestashop.add('/images/products/20108', files=[('image', file_name, content)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.5/site-packages/prestapyt/prestapyt.py", line 346, in add
    return self.add_with_url(full_url, content, files)
  File ".../lib/python3.5/site-packages/prestapyt/prestapyt.py", line 636, in add_with_url
    return _super.add_with_url(url, xml_content, files)
  File ".../lib/python3.5/site-packages/prestapyt/prestapyt.py", line 358, in add_with_url
    headers, data = self.encode_multipart_formdata(files)
  File ".../lib/python3.5/site-packages/prestapyt/prestapyt.py", line 508, in encode_multipart_formdata
    body = CRLF.join(L)
TypeError: sequence item 4: expected str instance, bytes found
```

**Comment by FFernandez-PlanetaTIC** [comment]
Please review #54
