### ISSUE TITLE
Release 0.9.1 on pypi

### ISSUE THREAD

**Issue by GuillaumeDesforges** [prestapyt/prestapyt#61]
Following #25

Could you please push `>=9.0` to pypi ? Current pypi version does not support Python 3

**Comment by pedrobaeza** [comment]
I don't know who have the key/credentials for pushing to pypi.

**Comment by GuillaumeDesforges** [comment]
maintainers on pypi are 

https://pypi.org/user/BenoitGuillot/ (sent him a msg on linkedin)
https://pypi.org/user/Guewen.Baconnier/ (sent him a tweet) 

oh that's actually @guewen

**Comment by guewen** [comment]
Hi,

I added a github action to automatically deploy on pypi on new tags, and added a 0.10.0 tag, so the new version is on https://pypi.org/project/prestapyt/

@pedrobaeza do you have a pypi account that I can add?

**Comment by pedrobaeza** [comment]
@guewen you can add `pbaeza`, thanks.
