### ISSUE TITLE
Exception on import prestapyt in python 3.7.9

### ISSUE THREAD

**Issue by anikeenko-viktor** [prestapyt/prestapyt#62]
It gives me `ModuleNotFoundError: No module named 'importlib.metadata'`
Should be `importlib_metadata` for python < 3.8

**Comment by R4F44L** [comment]
same issue here

**Comment by pedrobaeza** [comment]
Can you please propose a PR amending the problem?

**Comment by omalbastin** [comment]
PR created: https://github.com/prestapyt/prestapyt/pull/65
