### ISSUE TITLE
prestashop 1.7.6.8 support

### ISSUE THREAD

**Issue by progressify** [prestapyt/prestapyt#73]
I have used this library on a Prestashop site with this version.
I know, this library is not fully compatible, and in fact it not work 😂

What is the problem with this version?
I receive this error every time:

```
'HTTP XML response is not parsable : XML or text declaration not at start of entity: line 1, column 1. b\'\\t<?xml version="1.0" encoding="UTF-8"?>\\n<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">\\n<product>
```

**Comment by progressify** [comment]
after some days of testing, I see that problem is not related to the ps version or prestapyt, but it's a bug in one of the installed plugins.
I have deactivated this plugin and now all works well!

**Comment by Peppee99** [comment]
hi guys, I have some problem, wich pluging are you deactivated?
