### ISSUE TITLE
Prestapyt problem with authorization

### ISSUE THREAD

**Issue by jesiiu** [prestapyt/prestapyt#88]
Hello, I am trying to connect to prestapyt with my store and I always get Not Authorized.
I pass api_key in PrestaShopWebServiceDict init as your docs said, but I can't connect.
I try to do it using Postman and everything is fine. 
I think it's a problem with the lib, I'm not sure if the lib is sending the login request correctly, probably the "ws_key" field is missing in the request.
I will be really glad if you can help me :)

**Comment by jesiiu** [comment]
I took the liberty of reviewing the prestapyt code and found where the problem is

When creating a connection to Prestashop using PrestaShopWebServiceDict

line 149-150
        if not self.client.auth:
            self.client.auth = (api_key, '')

It should be built in a different way

       if not self.client.auth:
            self.client.auth = requests.get(url=self._api_url, params={"ws_key" : f"{self._api_key}"})

Prestashop API require key with param "ws_key" and it should be send in request params

**Comment by jesiiu** [comment]
One more 
In request you must add params to login 

            response = requests.request(
                method,
                url,
                data=data,
                headers=request_headers,
                params=self.credentials
            )

**Comment by antoni4040** [comment]
Hello! I had the same problem. Could you share a complete copy of your file?

**Comment by jesiiu** [comment]
> Hello! I had the same problem. Could you share a complete copy of your file?

Sorry but i dont have it :( 
I abandoned it and switched to c# :)

**Comment by jesiiu** [comment]
> Hello! I had the same problem. Could you share a complete copy of your file?

If you will have any problem with that just let me now and I will try to help you

**Comment by antoni4040** [comment]
It's ok. I got it fixed in a different way. There was a problem with the firewall, it didn't allow headless access. Thanks anyway!
